### ISSUE TITLE
CUSOLVERRF is broken with CUDA 12.0 

### ISSUE THREAD

**Issue by frapac** [exanauts/CUSOLVERRF.jl#8]
CUDA 12.0 has made some change in `cusparse`, apparently impacting CUSOLVERRF.
Also, the functions used in the backsolve have been deprecated and removed in CUDA 12.0.

**Comment by junyuan-chen** [comment]
Hi! @frapac Is there any plan of updating the package for CUDA 12 in the near future (a couple of months)? What CusolverRF does seem to be useful but I wonder whether you are going to make changes here in this package or do you think it makes sense to take this chance to add the interface to CUDA.jl? I would try to help in the latter case.

**Comment by frapac** [comment]
Currently, the plan is to update the package in the summer (if we have the manpower). It is just a matter of removing the deprecated functions with their equivalent in CUDA 12. 

So far, we don't have any plan to add this interface to CUDA.jl. The initial PR got discontinued: 
https://github.com/JuliaGPU/CUDA.jl/pull/828
Few people are interested by sparse linear solver on GPU, unfortunately.

**Comment by frapac** [comment]
Solved by #9
